# Generated by Django 3.0.4 on 2020-05-15 20:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.RegexValidator(message='Username must include English numbers and length of 10', regex='^[0-9]{10}$')], verbose_name='username')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, verbose_name='email address')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Manager'), (1, 'Doctor'), (2, 'Patient')], default=0)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('last_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('mobile_number', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Mobile number must be 09XXXXXXXXX', regex='^09[0-9]{9}$')])),
                ('address', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
                ('birth_date', models.DateField()),
                ('avatar', models.ImageField(default='../media/avatar.svg', upload_to='avatar/')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'male'), (1, 'female')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('last_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('phone_number', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Phone number must include English numbers and format of XXX-XXXXXXXX ', regex='^([0-9]{3})-([0-9]{8})$')])),
                ('mobile_number', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Mobile number must be 09XXXXXXXXX', regex='^09[0-9]{9}$')])),
                ('address', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
                ('birth_date', models.DateField()),
                ('speciality', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(default='../media/avatar.svg', upload_to='avatar/')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'male'), (1, 'female')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
