# Generated by Django 3.0.4 on 2020-05-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This advice already exist.'}, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This symptom already exist.'}, max_length=50, unique=True)),
                ('value', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This medicine already exist.'}, max_length=50, unique=True)),
                ('duration', models.DurationField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This disease already exist.'}, max_length=50, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('total', models.IntegerField()),
                ('remained', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_doctor', to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('turn', models.IntegerField()),
                ('advices', models.ManyToManyField(blank=True, to='appointment.Advice')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Calendar')),
                ('disease', models.ManyToManyField(blank=True, to='appointment.Disease')),
                ('medicines', models.ManyToManyField(blank=True, to='appointment.Medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='account.Patient')),
                ('symptoms', models.ManyToManyField(blank=True, to='appointment.Symptom')),
            ],
        ),
    ]
