# Generated by Django 3.0.4 on 2020-04-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This advice already exist.'}, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('visited', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_turn', to='account.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_turn', to='account.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(default=0)),
                ('name', models.CharField(error_messages={'unique': 'This symptom already exist.'}, max_length=50, unique=True)),
                ('value', models.FloatField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This medicine already exist.'}, max_length=50, unique=True)),
                ('duration', models.DurationField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This disease already exist.'}, max_length=50, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advices', models.ManyToManyField(to='appointment.Advice')),
                ('disease', models.ManyToManyField(to='appointment.Disease')),
                ('medicines', models.ManyToManyField(to='appointment.Medicine')),
                ('symptoms', models.ManyToManyField(to='appointment.Symptom')),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.Turn')),
            ],
        ),
    ]
